### ISSUE TITLE
multiple input files

### ISSUE THREAD

**Issue by only1chunts** [KirillKryukov/naf#7]
the ability to compress and uncompress more than 1 file at a time would be very useful.
e.g.being able to compress all files with suffix .fasta : 
$ naf ./*.fasta > .
Adding an option to keep or remove the old fasta after compression could also be helpful, (default to keep them), and a similar flag for keep or remove .naf version after decompression.

**Comment by KirillKryukov** [comment]
> the ability to compress and uncompress more than 1 file at a time would be very useful.
> e.g.being able to compress all files with suffix .fasta :
> $ naf ./*.fasta > .

I agree. This is a planned extension, hopefully to be added soon.

> Adding an option to keep or remove the old fasta after compression could also be helpful, (default to keep them), and a similar flag for keep or remove .naf version after decompression.

I'm less thrilled about this one, but it's a relatively small feature, so I will consider it.

Thanks for suggestions.

**Comment by KirillKryukov** [comment]
I added support for multi-file archives. It works analogously to gzipping a tar file: First the individual FASTA files are combined into a single [Multi-Multi-FASTA](https://github.com/KirillKryukov/mumu) file, which is then compressed with NAF. See [Compressing multiple files section](https://github.com/KirillKryukov/naf#compressing-multiple-files).
